### ISSUE TITLE
Please add Zabbix 3.0.x support ...

### ISSUE THREAD

**Issue by vrtareg** [gigatec/zabbixnotifier#10]
After updating to Zabbix 3.0.x System is not shown any more.

**Comment by vrtareg** [comment]
No Update ?
Does owner abandoned project ?

**Comment by interpeix** [comment]
Look at https://github.com/gigatec/zabbixnotifier/pull/12 

:)

**Comment by skreuter** [comment]
@interpeix Thank you! :)
