### ISSUE TITLE
There's no LICENSE file in the repository

### ISSUE THREAD

**Issue by dualbus** [gigatec/zabbixnotifier#7]
From the headers of some of the files, I assume the whole code is released under the BSD license, but there's no "LICENSE" file as these headers claim, so, is it possible to fork this project to make some updates/pull-requests?

**Comment by skreuter** [comment]
Hi dualbus,

you are free to fork and modify our code. We will be happy to pull it back and release it if you are finished.

Thx for your support!

Best regards
Stefan
