### ISSUE TITLE
Issue with Zabbix 3.0 LTS

### ISSUE THREAD

**Issue by joaquindlz** [gigatec/zabbixnotifier#9]
Hi!
There are a issue with version 3.0 LTS of Zabbix.
The System field is void in each Zabbix issue.

Best regards,
Joaquín

**Comment by interpeix** [comment]
Look at https://github.com/gigatec/zabbixnotifier/pull/12

:)

**Comment by skreuter** [comment]
@interpeix Thank you! :)
